//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileWebFormsApplication.MobileService1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="questionnaire", Namespace="http://schemas.datacontract.org/2004/07/RIS_lab6")]
    [System.SerializableAttribute()]
    public partial class questionnaire : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string brandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> furnitureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> incomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> mobile_existenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string professionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> readField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OS {
            get {
                return this.OSField;
            }
            set {
                if ((object.ReferenceEquals(this.OSField, value) != true)) {
                    this.OSField = value;
                    this.RaisePropertyChanged("OS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> age {
            get {
                return this.ageField;
            }
            set {
                if ((this.ageField.Equals(value) != true)) {
                    this.ageField = value;
                    this.RaisePropertyChanged("age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                if ((object.ReferenceEquals(this.brandField, value) != true)) {
                    this.brandField = value;
                    this.RaisePropertyChanged("brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> furniture {
            get {
                return this.furnitureField;
            }
            set {
                if ((this.furnitureField.Equals(value) != true)) {
                    this.furnitureField = value;
                    this.RaisePropertyChanged("furniture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> income {
            get {
                return this.incomeField;
            }
            set {
                if ((this.incomeField.Equals(value) != true)) {
                    this.incomeField = value;
                    this.RaisePropertyChanged("income");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> mobile_existence {
            get {
                return this.mobile_existenceField;
            }
            set {
                if ((this.mobile_existenceField.Equals(value) != true)) {
                    this.mobile_existenceField = value;
                    this.RaisePropertyChanged("mobile_existence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profession {
            get {
                return this.professionField;
            }
            set {
                if ((object.ReferenceEquals(this.professionField, value) != true)) {
                    this.professionField = value;
                    this.RaisePropertyChanged("profession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> read {
            get {
                return this.readField;
            }
            set {
                if ((this.readField.Equals(value) != true)) {
                    this.readField = value;
                    this.RaisePropertyChanged("read");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sex {
            get {
                return this.sexField;
            }
            set {
                if ((object.ReferenceEquals(this.sexField, value) != true)) {
                    this.sexField = value;
                    this.RaisePropertyChanged("sex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MobileService1.IMobileService")]
    public interface IMobileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/addQuestionnaire", ReplyAction="http://tempuri.org/IMobileService/addQuestionnaireResponse")]
        void addQuestionnaire(MobileWebFormsApplication.MobileService1.questionnaire quest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/addQuestionnaire", ReplyAction="http://tempuri.org/IMobileService/addQuestionnaireResponse")]
        System.Threading.Tasks.Task addQuestionnaireAsync(MobileWebFormsApplication.MobileService1.questionnaire quest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/statOS", ReplyAction="http://tempuri.org/IMobileService/statOSResponse")]
        int[] statOS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/statOS", ReplyAction="http://tempuri.org/IMobileService/statOSResponse")]
        System.Threading.Tasks.Task<int[]> statOSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/statRead", ReplyAction="http://tempuri.org/IMobileService/statReadResponse")]
        int statRead();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/statRead", ReplyAction="http://tempuri.org/IMobileService/statReadResponse")]
        System.Threading.Tasks.Task<int> statReadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/statPrice", ReplyAction="http://tempuri.org/IMobileService/statPriceResponse")]
        int statPrice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/statPrice", ReplyAction="http://tempuri.org/IMobileService/statPriceResponse")]
        System.Threading.Tasks.Task<int> statPriceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMobileServiceChannel : MobileWebFormsApplication.MobileService1.IMobileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobileServiceClient : System.ServiceModel.ClientBase<MobileWebFormsApplication.MobileService1.IMobileService>, MobileWebFormsApplication.MobileService1.IMobileService {
        
        public MobileServiceClient() {
        }
        
        public MobileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addQuestionnaire(MobileWebFormsApplication.MobileService1.questionnaire quest) {
            base.Channel.addQuestionnaire(quest);
        }
        
        public System.Threading.Tasks.Task addQuestionnaireAsync(MobileWebFormsApplication.MobileService1.questionnaire quest) {
            return base.Channel.addQuestionnaireAsync(quest);
        }
        
        public int[] statOS() {
            return base.Channel.statOS();
        }
        
        public System.Threading.Tasks.Task<int[]> statOSAsync() {
            return base.Channel.statOSAsync();
        }
        
        public int statRead() {
            return base.Channel.statRead();
        }
        
        public System.Threading.Tasks.Task<int> statReadAsync() {
            return base.Channel.statReadAsync();
        }
        
        public int statPrice() {
            return base.Channel.statPrice();
        }
        
        public System.Threading.Tasks.Task<int> statPriceAsync() {
            return base.Channel.statPriceAsync();
        }
    }
}
