//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIS_lab6
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionnaire
    {
        public int id { get; set; }
        public string sex { get; set; }
        public Nullable<int> age { get; set; }
        public string profession { get; set; }
        public Nullable<int> income { get; set; }
        public Nullable<int> mobile_existence { get; set; }
        public string brand { get; set; }
        public Nullable<int> price { get; set; }
        public string OS { get; set; }
        public Nullable<int> furniture { get; set; }
        public Nullable<int> read { get; set; }
    }
}
